// Generated by CoffeeScript 1.6.3
(function() {
  var $, move;

  $ = jQuery;

  move = function(keyID) {
    keyID = keyID;
    switch (keyID) {
      case 119:
        return {
          forward: 1
        };
      case 97:
        return {
          turn: 1
        };
      case 100:
        return {
          turn: -1
        };
      case 115:
        return {
          forward: -1
        };
      case 113:
        return {
          strafe: 1
        };
      case 101:
        return {
          strafe: -1
        };
      case 32:
        return {
          forward: 0
        };
      default:
        return console.log(keyID);
    }
  };

  $(document).ready(function() {
    alert("loaded!");
    return $("body").on("keypress", function(key) {
      return $.ajax({
        url: "http://127.0.0.1:8071/motion-control/update",
        data: move(key.which),
        dataType: "jsonp"
      });
    });
  });

}).call(this);
